name: my_icons
description: "Personal package with my FontAwesome unicode strings."
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/fa-light-300.ttf
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
